#!/bin/bash

# Setup script for security fixes testing
# This script helps you collect the necessary tokens and IDs

echo "🔧 Security Fixes Test Setup"
echo ""
echo "This script will help you collect the necessary tokens and IDs for testing."
echo ""

# Check if backend is running
echo "Checking if backend is running..."
if curl -s http://localhost:8080/api/v1/families > /dev/null 2>&1; then
    echo "✅ Backend is running"
else
    echo "❌ Backend is not running!"
    echo "   Please start the backend first:"
    echo "   cd backend && ./mvnw spring-boot:run"
    echo ""
    exit 1
fi

echo ""
echo "📋 To collect the required data:"
echo ""
echo "1. Open your app in a browser (http://localhost:5173 or your frontend URL)"
echo ""
echo "2. Open Browser Developer Tools (F12) → Console tab"
echo ""
echo "3. Run these commands in the console to get device tokens:"
echo ""
echo "   // For Family A (first browser/incognito):"
echo "   localStorage.getItem('deviceToken')"
echo ""
echo "   // For Family B (second browser/incognito):"
echo "   localStorage.getItem('deviceToken')"
echo ""
echo "4. To get Task/List IDs:"
echo "   - Open Network tab (F12 → Network)"
echo "   - Make a request (e.g., fetch all tasks or lists)"
echo "   - Check the response JSON for IDs"
echo ""
echo "5. Once you have the data, set environment variables:"
echo ""
echo "   export FAMILY_A_TOKEN='your-family-a-device-token'"
echo "   export FAMILY_B_TOKEN='your-family-b-device-token'"
echo "   export FAMILY_A_TASK_ID='task-id-from-family-a'"
echo "   export FAMILY_A_LIST_ID='list-id-from-family-a'"
echo ""
echo "6. Then run the test script:"
echo "   ./test_security_fixes.sh"
echo ""
echo "---"
echo ""
echo "💡 Quick test via browser console:"
echo ""
echo "   // Test cross-family access (should fail):"
echo "   fetch('http://localhost:8080/api/v1/daily-tasks/{FAMILY_A_TASK_ID}', {"
echo "     method: 'PATCH',"
echo "     headers: {"
echo "       'Content-Type': 'application/json',"
echo "       'X-Device-Token': '{FAMILY_B_DEVICE_TOKEN}'"
echo "     },"
echo "     body: JSON.stringify({"
echo "       name: 'Hacked Task',"
echo "       description: 'Test',"
echo "       daysOfWeek: ['MONDAY'],"
echo "       isRequired: true,"
echo "       xpPoints: 10"
echo "     })"
echo "   })"
echo "   .then(r => r.json())"
echo "   .then(console.log)"
echo "   .catch(console.error)"
echo ""
